### ISSUE TITLE
Discord Invite Link Expired

### ISSUE THREAD

**Issue by emoisback** [Ultimeit/palguard_anticheat#1]
can you give invitation link life time

**Comment by Ultimeit** [comment]
> can you give invitation link life time

![image](https://github.com/Ultimeit/palguard_anticheat/assets/49292935/578d5f58-f856-4f3d-88c2-e1070030a465)
It is life time though, just tested and it does still works. Here's a new one anyway: https://discord.gg/dXnrrcKUR5
